grpc:
  server:
    port: 59091

spring:
  application:
    name: hubRouter
  config:
    uri: http://localhost:8888
    fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/