logging:
  level:
    ru.yandex.practicum: TRACE
    org:
      springframework: ERROR
      apache.kafka: ERROR

aggregator:
  kafka:
    topics:
      telemetry-sensors: telemetry.sensors.v1
      telemetry-snapshots: telemetry.snapshots.v1

    producer:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": "telemetry.collection"
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.kafka.GeneralAvroSerializer


    consumer:
      properties:
        "group.id": "aggregator-consumer-group"
        "auto-offset-reset": earliest
        "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
        #      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        "value.deserializer": ru.yandex.practicum.kafka.SensorEventDeserializer
        bootstrap.servers": localhost:9092