kafkaServer: localhost:9092
sensorEventTopic: telemetry.sensors.v1
hubEventTopic: telemetry.hubs.v1

spring:
  application:
    name: collector

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/