kafkaServer: localhost:9092
sensorEventTopic: telemetry.sensors.v1
hubEventTopic: telemetry.hubs.v1

grpc:
  server:
    port: 59091

spring:
  application:
    name: collector
  config:
    uri: http://localhost:8888
    fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true