spring:
  application:
    name: analyzer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart
    username: user
    password: pass

grpc:
  client:
    hub-router:
      address: discovery:///hubRouter
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  hub-consumer-properties:
    bootstrap.servers: localhost:9092
    group.id: hub.analyzing
    client.id: hubConsumer
    key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
    value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
    enable.auto.commit: false
  hub-topics:
    - telemetry.hub.v1
  hub-consume-attempt-timeout: 1000

  snapshot-consumer-properties:
    bootstrap.servers: localhost:9092
    group.id: snapshot.analyzing
    client.id: snapshotConsumer
    key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
    value.deserializer: ru.yandex.practicum.kafka.deserializer.SensorSnapshotDeserializer
    enable.auto.commit: false
  snapshot-topics:
    - telemetry.snapshots.v1
  snapshot-consume-attempt-timeout: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/