spring:
  application:
    name: warehouse
  config:
    import: "configserver:"
    cloud:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

  eureka:
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    instance:
      preferIpAddress: true
      hostname: localhost
      instance-id: "${spring.application.name}:${random.value}"
      leaseRenewalIntervalInSeconds: 10
    server:
      port: 0

